/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airport;

import com.jtattoo.plaf.graphite.GraphiteLookAndFeel;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author manuk
 */
public class APMainFrame extends javax.swing.JFrame {
    Metodes mt = new Metodes(this);

    /**
     * Creates new form APMainFrame
     */
    public APMainFrame() {
        try {
            UIManager.setLookAndFeel(new GraphiteLookAndFeel());
            JFrame.setDefaultLookAndFeelDecorated(true);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(APMainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon("E:\\Program\\AirPort\\src\\airport\\nTE7pxkqc.gif").getImage());
        mt.show();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panButton = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnShow = new javax.swing.JButton();
        panContent = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listTrain = new javax.swing.JList<>();
        combSearchby = new javax.swing.JComboBox<>();
        txfldSearch = new javax.swing.JTextField();
        comboSort = new javax.swing.JComboBox<>();
        menuBar = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        mnItemSave = new javax.swing.JMenuItem();
        mnItemExit = new javax.swing.JMenuItem();
        menuEdit = new javax.swing.JMenu();
        menuHelp = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAdd.setText("Add");
        btnAdd.setName("btnAdd"); // NOI18N
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnShow.setText("Show All");
        btnShow.setName("btnShow"); // NOI18N
        btnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panButtonLayout = new javax.swing.GroupLayout(panButton);
        panButton.setLayout(panButtonLayout);
        panButtonLayout.setHorizontalGroup(
            panButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panButtonLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnShow)
                .addContainerGap(521, Short.MAX_VALUE))
        );
        panButtonLayout.setVerticalGroup(
            panButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panButtonLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(panButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnShow))
                .addContainerGap())
        );

        getContentPane().add(panButton, java.awt.BorderLayout.CENTER);

        listTrain.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "base" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listTrain.setToolTipText("");
        listTrain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listTrainMouseClicked(evt);
            }
        });
        listTrain.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listTrainValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listTrain);

        combSearchby.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Search by", "Destination ", "Price", "Time", "Number" }));
        combSearchby.setToolTipText("Search by");
        combSearchby.setName("Search by"); // NOI18N
        combSearchby.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combSearchbyItemStateChanged(evt);
            }
        });
        combSearchby.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combSearchbyActionPerformed(evt);
            }
        });

        txfldSearch.setText("Text");
        txfldSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txfldSearchMouseEntered(evt);
            }
        });

        comboSort.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sort by", "Destination", "Price", "Time", "Number" }));
        comboSort.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboSortItemStateChanged(evt);
            }
        });
        comboSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSortActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panContentLayout = new javax.swing.GroupLayout(panContent);
        panContent.setLayout(panContentLayout);
        panContentLayout.setHorizontalGroup(
            panContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(panContentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(panContentLayout.createSequentialGroup()
                        .addComponent(comboSort, 0, 103, Short.MAX_VALUE)
                        .addGap(259, 259, 259)
                        .addComponent(combSearchby, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txfldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );
        panContentLayout.setVerticalGroup(
            panContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panContentLayout.createSequentialGroup()
                .addGroup(panContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combSearchby, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboSort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        combSearchby.getAccessibleContext().setAccessibleName("Search by");

        getContentPane().add(panContent, java.awt.BorderLayout.PAGE_START);

        menuBar.setBorderPainted(false);

        menuFile.setText("File");

        mnItemSave.setText("Save");
        mnItemSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemSaveActionPerformed(evt);
            }
        });
        menuFile.add(mnItemSave);

        mnItemExit.setText("Exit");
        mnItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemExitActionPerformed(evt);
            }
        });
        menuFile.add(mnItemExit);

        menuBar.add(menuFile);

        menuEdit.setText("Edit");
        menuBar.add(menuEdit);

        menuHelp.setText("Help");
        menuBar.add(menuHelp);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        AddFrame add = new AddFrame(this, true);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowActionPerformed
                 mt.show();
    }//GEN-LAST:event_btnShowActionPerformed

    private void mnItemSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemSaveActionPerformed
                   mt.save();
    }//GEN-LAST:event_mnItemSaveActionPerformed

    private void mnItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_mnItemExitActionPerformed

    private void combSearchbyItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combSearchbyItemStateChanged
       // mt.searchBy();
    }//GEN-LAST:event_combSearchbyItemStateChanged

    private void comboSortItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboSortItemStateChanged
         //mt.sortBy();
    }//GEN-LAST:event_comboSortItemStateChanged

    private void listTrainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listTrainMouseClicked
mt.listActions();        
// TODO add your handling code here:
    }//GEN-LAST:event_listTrainMouseClicked

    private void listTrainValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listTrainValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_listTrainValueChanged

    private void combSearchbyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combSearchbyActionPerformed
        mt.searchBy();
        // TODO add your handling code here:
    }//GEN-LAST:event_combSearchbyActionPerformed

    private void comboSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSortActionPerformed
       mt.sortBy();
        // TODO add your handling code here:
    }//GEN-LAST:event_comboSortActionPerformed

    private void txfldSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txfldSearchMouseEntered
this.txfldSearch.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_txfldSearchMouseEntered

    /**
     * @param args the command line arguments
     */
    

        /* Create and display the form */
       
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnShow;
    protected javax.swing.JComboBox<String> combSearchby;
    protected javax.swing.JComboBox<String> comboSort;
    private javax.swing.JScrollPane jScrollPane1;
    protected static javax.swing.JList<String> listTrain;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuEdit;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenuItem mnItemExit;
    private javax.swing.JMenuItem mnItemSave;
    private javax.swing.JPanel panButton;
    private javax.swing.JPanel panContent;
    protected javax.swing.JTextField txfldSearch;
    // End of variables declaration//GEN-END:variables

}